src/Entity/Hospital.php
<?php

namespace App\Entity;

use App\Repository\HospitalRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=HospitalRepository::class)
 */
class Hospital
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nombre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $codigoHosp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $direccion;

    /**
     * @ORM\OneToMany(targetEntity=Persona::class, mappedBy="hospitalNac", orphanRemoval=true)
     */
    private $personas;

    public function __construct()
    {
        $this->personas = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->Nombre;    
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): self
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getCodigoHosp(): ?string
    {
        return $this->codigoHosp;
    }

    public function setCodigoHosp(string $codigoHosp): self
    {
        $this->codigoHosp = $codigoHosp;

        return $this;
    }

    public function getDireccion(): ?string
    {
        return $this->direccion;
    }

    public function setDireccion(string $direccion): self
    {
        $this->direccion = $direccion;

        return $this;
    }

    /**
     * @return Collection<int, Persona>
     */
    public function getPersonas(): Collection
    {
        return $this->personas;
    }

    public function addPersona(Persona $persona): self
    {
        if (!$this->personas->contains($persona)) {
            $this->personas[] = $persona;
            $persona->setHospitalNac($this);
        }

        return $this;
    }

    public function removePersona(Persona $persona): self
    {
        if ($this->personas->removeElement($persona)) {
            // set the owning side to null (unless already changed)
            if ($persona->getHospitalNac() === $this) {
                $persona->setHospitalNac(null);
            }
        }

        return $this;
    }
}

src/Controller/ProfesionalesController.php
<?php

namespace App\Controller;

use App\Entity\Alcance;
use App\Entity\Persona;
use App\Entity\PersonaContacto;
use App\Entity\PersonaDomicilio;
use App\Entity\Profesional;
use App\Entity\ProfesionalEspecialista;
use App\Entity\ProfesionalRegistracion;
use App\Entity\ProfesionalRegistracionArchivo;
use App\Entity\TipoMatricula;
use App\Form\CombinatedFormType;
use App\Form\PersonaContactoType;
use App\Form\PersonaType;
use App\Form\ProfesionalType;
use App\Repository\AlcanceRepository;
use App\Repository\EspecialidadRepository;
use App\Repository\PersonaContactoRepository;
use App\Repository\PersonaDomicilioRepository;
use App\Repository\PersonaRepository;
use App\Repository\ProfesionalEspecialistaRepository;
use App\Repository\ProfesionalRegistracionArchivoRepository;
use App\Repository\ProfesionalRegistracionRepository;
use App\Repository\ProfesionalRepository;
use App\Repository\UsuarioRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @Route("/profesionales")
 */
class ProfesionalesController extends AbstractController
{
    /**     
     *@Route("/", name="app_profesionales_index", methods={"GET"})
     */
    public function index(ProfesionalRepository $profesionalRepository): Response
    {    
        $profesionales =$profesionalRepository->findBy(['borrado' => "0"]);        

        return $this->render('profesionales/index.html.twig', [
            'profesionales' => $profesionales,
        ]);
    }


    /**
     * @Route("/new", name="app_profesionales_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager, UsuarioRepository $usuarioRepository, AlcanceRepository $repoAlcance): Response
    {
        //Identificacion para DELETE y usuario de CARGA
        $userIdentifier=$this->getUser()->getUserIdentifier();
        $usuario = $usuarioRepository->findOneBy(["dni" => $userIdentifier]);
        $id_usuario = $usuario->getId();

        //Creacion de instancias de todas las entidades a crear
        $profesional = new Profesional();
        $persona = new Persona();
        $contacto = new PersonaContacto();
        $domicilio = new PersonaDomicilio();
        $registracion = new ProfesionalRegistracion();
        $archivo = new ProfesionalRegistracionArchivo();
        $especialista = new ProfesionalRegistracionArchivo();
    
        //Formulario Combinado
        $form = $this->createForm(CombinatedFormType::class);        
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {           
                
                //Levantar datos del formulario para las instancias
                $contacto = $form->get('form_contacto')->getData();
                $domicilio = $form->get('form_domicilio')->getData();
                $persona = $form->get('form_persona')->getData();
                $profesional = $form->get('form_profesional')->getData();
                $registracion = $form->get('form_reg')->getData();
                $especialista = $form->get('form_especialista')->getData();

               
                //Pisa datos con objetos correspondietes
                $profesional->setPersona($persona);                
                $contacto->setPersona($persona);
                
                $domicilio->setPersona($persona);
                $domicilio->setUsuarioActualizaId($usuario);

                $especialista->setFechaActualizacion(new \DateTime());
                $especialista->setProfesional($profesional);

                

                //RegistracionProfesional. Se lo carga en detalle. VER TEMA DE ALCANCE.
                $registracion->setProfesional($profesional);
                $registracion->setFechaRegistracion(new \DateTime());
                            $Matricula = $profesional->getTipoMatricula();
                            $id_tipoMatricula = $Matricula->getId();
                            if($id_tipoMatricula == TipoMatricula::MEDICO){
                                $alcance_id = Alcance::DEFUNCIONES;
                            }else{
                                $alcance_id = Alcance::NACIMIENTOS;
                            }
                $alcance = $repoAlcance->findOneBy(['id' => $alcance_id]);
                $registracion->setAlcance($alcance);
                $entityManager->persist($registracion);      

                
                
                //Proceso de carga de archivo
                $archivo = $form->get('form_archivo')->getData(); 
                        
                if ($archivo) {
                    $file=$_FILES['combinated_form'];
                    if($file["name"]["form_archivo"]["nombreArchivo"]){
                        try {                    
                            $nombre_archivo= $file["name"]["form_archivo"]["nombreArchivo"];
                            
                            $extension = explode(".", $nombre_archivo);
                            $ext = trim($extension[1]);                        
                            $nombre_unico = uniqid() . '_' . time();
                            $nombre_archivo = $nombre_unico . '.' . $ext;
                            $path = '../public/imagenes/' . $nombre_archivo . '';
                            move_uploaded_file($file["tmp_name"]["form_archivo"]["nombreArchivo"], $path);

                            $archivo->setNombreArchivo($nombre_archivo);                        
                            $archivo->setFechaCarga(new \DateTime());
                            $archivo->setPath($path);
                            $archivo->setTipoArchivo($ext);
                            $archivo->setProfesionalRegistracion($registracion);
                            $entityManager->persist($archivo);
                            
                        } catch (FileException $e) {
                            throw new \Exception($e);
                        }      
                    }                    
                }              
                
                //Persistiendo             
                $entityManager->persist($persona);
                $entityManager->persist($profesional);
                $entityManager->persist($contacto);
                $entityManager->persist($domicilio);                                                              
                $entityManager->persist($especialista);                               
                $entityManager->flush();       
                return $this->redirectToRoute('app_profesionales_index', [], Response::HTTP_SEE_OTHER);                       
        }

        return $this->renderForm('profesionales/new.html.twig', [
            'form' => $form,
             //Este $id es el que va a pasar al Javascript para setear el campo Usuario de carga..
            'id_usuario' => $id_usuario,    
            'archivo'=> $archivo->getNombreArchivo()
        ]);
    }



    /**
     * @Route("/{id}", name="app_profesionales_show", methods={"GET"})
     */
    public function show ($id, ProfesionalEspecialistaRepository $especialistaRepository, ProfesionalRegistracionArchivoRepository $archivoRepo, ProfesionalRegistracionRepository $profesionalRegistracionRepository,ProfesionalRepository $profesionalRepository, PersonaRepository $personaRepository, PersonaContactoRepository $personaContactoRepository, PersonaDomicilioRepository $personaDomicilioRepository): Response   
    {   
        //Se buscan por los objetos correspondietes por repositorio usando ID de Profesional
        $profesional = $profesionalRepository->findOneBy(["id" => $id]);
        $persona = $profesional->getPersona();       
        $contacto = $personaContactoRepository->findOneBy(["persona" => $persona]);
        $domicilio = $personaDomicilioRepository->findOneBy(["persona" => $persona]);  
        $registracion = $profesionalRegistracionRepository->findOneBy(["profesional" => $id]);
        $archivo = $archivoRepo->findOneBy(["profesionalRegistracion" => $registracion->getId()]);
        $especialista = $especialistaRepository->findOneBy(["profesional" => $id]);

        //Se Crea el formulario y se carga con los datos de los objetos tomados arriba
        $form = $this->createForm(CombinatedFormType::class,  [
            'form_profesional' => $profesional,
            'form_persona' => $persona,
            'form_contacto' => $contacto,
            'form_domicilio' => $domicilio,
            'form_reg' => $registracion,
            'form_archivo' => $archivo,
            'form_especialista' => $especialista,
        ]);      

        if($archivo == NULL){
            return $this->renderForm('profesionales/show.html.twig', [
                'form'=>$form,
                'archivo'=> "null.png"
            ]);    
        }else{
            return $this->renderForm('profesionales/show.html.twig', [
                'form'=>$form,
                'archivo'=> $archivo->getNombreArchivo()
            ]);            
        }
        
    }



    /**
     * @Route("/{id}/edit", name="app_profesionales_edit", methods={"GET", "POST"})
     */

templates/profesionales/_delete_form.html.twig
<form method="post" action="{{ path('app_profesionales_delete', {'id': id}) }}" onsubmit="return confirm('¿Esta seguro que desea eliminar?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ id) }}">
    <button class="btn btn-danger">Eliminar <i class="fa-regular fa-trash-can"></i></button>
</form>

templates/profesionales/_form.html.twig
{# Esto es un formulario generico en dos columnas, se utliza para Show, New y Edit #}

<style>
  table{
    width: 100%;                   
  }

  span{                   
    font-weight: bold;        
  }

  td{        
    height: 3em;
    text-align: left;
  }

  .col{
    text-align: left;
  }
  
</style>

  {{ form_start(form) }}
<div class="container text-center">
      
      <div class="row align-items-start">

              {# Fila 1 Columna 1 #}
              <div class="col">
                <h2 class="form-text" style="font-size: x-large;">Datos personales</h2>
                <br>
                <br>                 
                    <table>
                      <tr>
                        <td><span class="form-text" >Tipo de documento</span></td>
                        <td>{{ form_widget(form.form_persona.tipoDocumento, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'Tipo de documento'}}) }}</td>            
                      </tr>
                      <tr>
                        <td><span class="form-text" >N° de documento</span></td>
                        <td>{{ form_widget(form.form_persona.numeroDocumento, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'Numero de documento'}}) }}</td>            
                      </tr>
                      <tr>
                        <td><span class="form-text">Apellido</span></td>
                        <td>{{ form_widget(form.form_persona.apellido, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'Apellido'}}) }}</td>            
                      </tr>
                      <tr>
                        <td><span class="form-text">Nombre</span></td>
                        <td>{{ form_widget(form.form_persona.nombre, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'Nombre'}}) }}</td>            
                      </tr>
                      <tr>
                        <td><span class="form-text">Fecha de nacimiento</span></td>
                        <td>{{ form_widget(form.form_persona.fechaNacimiento, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'Fecha de Nacimiento'}}) }}</td>            
                      </tr>
                      <tr>
                        <td><span class="form-text">CUIL</span></td>
                        <td>{{ form_widget(form.form_persona.cuil, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'Cuil'}}) }}</td>            
                      </tr>
                      <tr>
                        <td><span class="form-text">Sexo</span></td>
                        <td>{{ form_widget(form.form_persona.sexo, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'Sexo'}}) }}</td>            
                      </tr>
                      <tr>
                        <td><span class="form-text">País</span></td>
                        <td>{{ form_widget(form.form_persona.pais, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'Pais'}}) }}</td>            
                      </tr>
                    </table> 
              </div>
                 

              <div class="separador"></div>     


              {# Fila 1 Columna 2 #}

              <div class="col">
                <h2 class="form-text" style="font-size: x-large;">Datos profesionales</h2>
                <br>
                <br> 
                    <table>                      
                      <tr>
                        <td><span class="form-text">Tipo de matricula</span></td>
                        <td>{{ form_widget(form.form_profesional.tipoMatricula, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'Tipo de matricula'}}) }}</td>
                      </tr>
                      <tr>
                        <td><span class="form-text">Matricula</span></td>
                        <td>{{ form_widget(form.form_profesional.matricula, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'N° de matricula'}}) }}</td>
                      </tr>          
                      <tr>
                        <td><span class="form-text">Especialidad</span></td>
                        <td>{{ form_widget(form.form_especialista.especialidad, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'Tipo de matricula'}}) }}</td>
                      </tr>  
                      <tr>
                        <td><span class="form-text">Fallecido</span></td>
                        <td>{{ form_widget(form.form_profesional.fallecido, {'attr': {'class': 'form-control form-control-sm'}}) }}</td>
                      </tr>
                      <tr>
                        <td><span class="form-text">Fecha fallec.</span></td>
                        <td> {{ form_widget(form.form_profesional.fechaFallecido, {'attr': {'class': 'form-control form-control-sm'}}) }}</td>
                      </tr>
                      <tr>
                        <td><span class="form-text">Habilitado</span></td>
                        <td>{{ form_widget(form.form_profesional.habilitado, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'Habilitado'}}) }}</td>
                      </tr>
                      <tr>
                        <td><span class="form-text">Fecha de alta</span></td>
                        <td>{{ form_widget(form.form_profesional.fechaAlta, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'Fecha de alta'}}) }}</td>
                      </tr>
                      <tr>
                        <td><span class="form-text">Fecha de baja</span></td>
                        <td>{{ form_widget(form.form_profesional.fechaBaja, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'Fecha de baja'}}) }}</td>
                      </tr>
                      <tr>
                        <td><span class="form-text">Fecha de carga</span></td>
                        <td>{{ form_widget(form.form_profesional.fechaCarga, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'Fecha de carga'}}) }}</td>
                      </tr>
                      
                      <tr>
                        <td><span class="form-text">Usuario de carga</span></td>
                        <td>{{ form_widget(form.form_profesional.usuario, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'Usuario de carga'}}) }}</td>
                      </tr>
                       
                      <tr>
                        <td><span class="form-text">Distrito</span></td>
                        <td>{{ form_widget(form.form_profesional.distrito, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'Distrito'}}) }}</td>
                      </tr>   
                      <tr>
                        <td><span class="form-text">Origen</span></td>
                        <td>{{ form_widget(form.form_reg.origenRegistracion, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'Distrito'}}) }}</td>
                      </tr>   
                      <tr>
                        <td><span class="form-text">Delegacion</span></td>
                        <td>{{ form_widget(form.form_reg.delegacion, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'Delegacion'}}) }}</td>
                      </tr> 
                      
                    </table>                    
              </div>             



              <div class="separador"></div>      
              
     

              {# Fila 1 Columna 3 #}
              <div class="col">
                <h2 class="form-text" style="font-size: x-large;">Datos de contacto</h2>
                <br>
                <br>                 
                    <table>
                      <tr>
                        <td><span class="form-text" >Telefono Fijo</span></td>
                        <td>{{ form_widget(form.form_contacto.telefonoFijo, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'Telefono fijo'}}) }}</td>            
                      </tr>
                      <tr>
                        <td><span class="form-text" >Telefono Móvil</span></td>
                        <td>{{ form_widget(form.form_contacto.telefonoMovil, {'attr': {'class': 'form-control form-control-sm', 'placeholder': '(11) xxxx-xxxx'}}) }}</td>            
                      </tr>
                      <tr>
                        <td><span class="form-text">E-mail</span></td>
                        <td>{{ form_widget(form.form_contacto.mail, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'ejemplo@mail.com'}}) }}</td>            
                      </tr>
                
                      <tr>
                        <td><span class="form-text">Calle</span></td>
                        <td>{{ form_widget(form.form_domicilio.calle, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'Calle'}}) }}</td>
                      </tr>
                      <tr>
                        <td><span class="form-text">Altura</span></td>
                        <td>{{ form_widget(form.form_domicilio.numero, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'Altura', 'required': false}}) }}</td>
                      </tr>
                      <tr>
                        <td><span class="form-text">Piso</span></td>
                        <td> {{ form_widget(form.form_domicilio.piso, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'Piso', 'required': false}}) }}</td>
                      </tr>
                      <tr>
                        <td><span class="form-text">Departamento</span></td>
                        <td>{{ form_widget(form.form_domicilio.departamento, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'Departamento','required': false}}) }}</td>
                      </tr>                    
                      <tr>
                        <td><span class="form-text">Fecha de actualizacion</span></td>
                        <td>{{ form_widget(form.form_domicilio.fechaActualizacion, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'fechaActualizacion'}}) }}</td>
                      </tr>
                      <tr>
                        <td><span class="form-text">Localidad</span></td>
                        <td>{{ form_widget(form.form_domicilio.localidad, {'attr': {'class': 'form-control form-control-sm', 'placeholder': 'Localidad', 'required': true}}) }}</td>
                      </tr> 
                    </table>
              </div>

      </div>



      <br>
      <div class="separadorHorizontal"></div>
      <br>



      <div class="row align-items-start">

              <div class="col">
                <h2 class="form-text" style="font-size: x-large;">Archivo</h2>
                <br>                     
                  {{ form_widget(form.form_archivo.nombreArchivo, {'attr': {'class': 'form-control form-control-sm'  }}) }}
              </div>
              
              <div class="col">                 
                <br>    
                <img id="previsualizacion" src="{{asset('imagenes/'~ archivo)}}" alt="Vista previa" style="max-width: 30em; max-height: 30em">      
              </div>              
      </div>

  <br>
  <br>
              
                
                                        
  <button class="btn btn-primary" id="btn_form">{{ button_label|default('Guardar') }}</button>  


    
                          

  
{{ form_end(form) }} 

</div>
{# Columna Principal #}

        
    
    

templates/profesionales/disable_inputs.html.twig
{# Este script deshabilita las fechas que no son reelevantes. Tambien customiza un listado de usuarios. #}


<script>
        let usuario = document.getElementById("combinated_form_form_profesional_usuario");   
        let id_usuario = {{id_usuario}};

        for (let i = 0; i < usuario.options.length; i++) {
            if (usuario.options[i].value !== String(id_usuario)) {
                usuario.remove(i);
                i--; // Disminuir el índice para compensar la eliminación de la opción
            }
        }      
   

        let fallecido = document.getElementById("combinated_form_form_profesional_fallecido");
        let fechaFallecido = document.getElementById("combinated_form_form_profesional_fechaFallecido");

        let habilitado = document.getElementById("combinated_form_form_profesional_habilitado");
        let fechaAlta = document.getElementById("combinated_form_form_profesional_fechaAlta");
        let fechaBaja = document.getElementById("combinated_form_form_profesional_fechaBaja");

        let fechaCarga = document.getElementById("combinated_form_form_profesional_fechaCarga");       

        fechaFallecido.readOnly = true;
        fechaFallecido.disabled = true;
        fechaBaja.readOnly = true;
        fechaBaja.disabled = true;

        fallecido.addEventListener("change", function() {
            if (fallecido.value === "SI") {
                fechaFallecido.readOnly = false;
                fechaFallecido.disabled = false;
            } else {
                fechaFallecido.readOnly = true;
                fechaFallecido.disabled = true;

            }
            });
        
        habilitado.addEventListener("change", function() {
            if (habilitado.value === "SI") {
                fechaAlta.readOnly = false;
                fechaAlta.disabled = false;
                fechaBaja.readOnly = true;
                fechaBaja.disabled = true;
            } else {
                fechaAlta.readOnly = true;
                fechaAlta.disabled = true;
                fechaBaja.readOnly = false;
                fechaBaja.disabled = false;
            }
        
            });    
    </script>

  

templates/profesionales/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar medico{% endblock %}

{% block encabezado %}
    Editar medico
{% endblock %}

{% block main %}

    {{ include('profesionales/_form.html.twig', {'button_label': 'Modificar'}) }}    
    {{ include('profesionales/_delete_form.html.twig') }}
    {{ include('profesionales/disable_inputs.html.twig') }}
    {{ include('profesionales/previsualizcion_archivos.html.twig') }} 
    
{% endblock %}

templates/profesionales/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Medicos y Obstetras{% endblock %}

{% block encabezado %}
    Medicos y Obstetras
{% endblock %}

{% block main %}
    
    <table class="table is-striped" id="table">
        <thead>
            <tr>
                <th>Matricula</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Tipo de matricula</th>
                <th>Distrito</th>                
                <th>Fallecido</th>                
                <th>Ver/Modificar</th>
            </tr>
        </thead>
        <tbody>
        {% for profesional in profesionales %}
            <tr>
                <td>{{ profesional.matricula }}</td>
                <td>{{ profesional.persona.nombre }}</td>
                <td>{{ profesional.persona.apellido }}</td>
                <td>{{ profesional.tipoMatricula.tipo }}</td>
                <td>{{ profesional.distrito.nombre }}</td>
                <td>{{ profesional.fallecido }}</td>
                <td>
                    <a title="Visualizar" href="{{ path('app_profesionales_show', {'id': profesional.id}) }} "> <i class="fa-solid fa-eye"></i></a>                
                    <a title="Modificar" href="{{ path('app_profesionales_edit', {'id': profesional.id}) }}"><i class="fa-regular fa-pen-to-square"></i></a>                  
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">No se encontraron datos</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <style>
        select{
            border-color: #009aae;
            box-shadow: 0 0 0 0.125em rgba(0,154,174,.25);        
        }
    </style>


{% endblock %}

templates/profesionales/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Alta de profesional{% endblock %}

{% block encabezado %}
    Alta de profesional
{% endblock %}

{% block main %}


    {{ include('profesionales/_form.html.twig') }}


    <script>
        let usuario = document.getElementById("combinated_form_form_profesional_usuario");   
        let id_usuario = {{id_usuario}};

        for (let i = 0; i < usuario.options.length; i++) {
            if (usuario.options[i].value !== String(id_usuario)) {
                usuario.remove(i);
                i--; // Disminuir el índice para compensar la eliminación de la opción
            }
        }      
   

        let fallecido = document.getElementById("combinated_form_form_profesional_fallecido");
        let fechaFallecido = document.getElementById("combinated_form_form_profesional_fechaFallecido");

        let habilitado = document.getElementById("combinated_form_form_profesional_habilitado");
        let fechaAlta = document.getElementById("combinated_form_form_profesional_fechaAlta");
        let fechaBaja = document.getElementById("combinated_form_form_profesional_fechaBaja");

        let fechaCarga = document.getElementById("combinated_form_form_profesional_fechaCarga");       

        fechaFallecido.readOnly = true;
        fechaFallecido.disabled = true;
        fechaBaja.readOnly = true;
        fechaBaja.disabled = true;

        fallecido.addEventListener("change", function() {
            if (fallecido.value === "SI") {
                fechaFallecido.readOnly = false;
                fechaFallecido.disabled = false;
            } else {
                fechaFallecido.readOnly = true;
                fechaFallecido.disabled = true;

            }
            });
        
        habilitado.addEventListener("change", function() {
            if (habilitado.value === "SI") {
                fechaAlta.readOnly = false;
                fechaAlta.disabled = false;
                fechaBaja.readOnly = true;
                fechaBaja.disabled = true;
            } else {
                fechaAlta.readOnly = true;
                fechaAlta.disabled = true;
                fechaBaja.readOnly = false;
                fechaBaja.disabled = false;
            }
        
            });    
    </script>
    

{% endblock %}